language: node_js

node_js:
  - "10.15.1"

dist: trusty

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run test
  - npm run build
  - git add dist -f

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
